### ISSUE TITLE
called Option::unwrap()` on a `None` value' error

### ISSUE THREAD

**Issue by VPaulV** [radare/radeco-lib#30]
On some binaries radeco fails at the  [*] Parsing ESIL step.
[malware_sample.zip: password - infected](https://github.com/radare/radeco-lib/files/271766/malware_sample.zip)

```
thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value', ../src/libcore/option.rs:330
stack backtrace:
   1:     0x7f9f2b2bca08 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f9f2b2bc80e - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f9f2b2bb0c6 - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   4:     0x7f9f2b2ba8f5 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   5:     0x7f9f2b2ce0c4 - panicking::panic_fmt::h98b8cbb286f5298alcM
   6:     0x7f9f2b2ce128 - panicking::panic::h4265c0105caa1121SaM
   7:     0x7f9f2b1fdc8f - frontend::parser::Parser::emit_insts::ha2af8ea72bd93276qdi
   8:     0x7f9f2b1a84b5 - utils::Runner::run::h02fcf46af8b11481sOa
   9:     0x7f9f2b176a12 - main::h9cef0bb901591b93Ohb
  10:     0x7f9f2b2cb684 - sys_common::unwind::try::try_fn::h14622312129452522850
  11:     0x7f9f2b2c8d8b - __rust_try
  12:     0x7f9f2b18902c - main
  13:     0x7f9f2a5937af - __libc_start_main
  14:     0x7f9f2b176438 - _start
  15:                0x0 - <unknown>
```

**Comment by v-p-b** [comment]
Getting similar result on the main function of `/bin/ls`:

```
[0x004028c0]> #!pipe RUST_BACKTRACE=1 radeco -p 'r2,esil,cfg'
[*] Starting radeco with config: 
Name: ls.run
Binary: /bin/ls
Address: 0x4028c0
Pipeline:
    - r2
    - Parse ESIL
    - Control Flow Graph Construction
Output: ./ls_out
[*] Reading from R2
[*] Parsing ESIL
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7f1016b1cab0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7f1016b20dab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7f1016b20a33 - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7f1016b0f94f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7f1016b10b58 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7f1016b1be71 - rust_begin_unwind
   7:     0x7f1016b5782f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7f1016b57b38 - core::panicking::panic::hdbcf9a6d5c170498
   9:     0x7f1016911375 - _<std..option..Option<T>>::unwrap::h30c92445d405f982
                        at ../src/libcore/macros.rs:21
  10:     0x7f101690540e - radeco_lib::frontend::parser::Parser::parse_str::hd695cc1596b93feb
                        at /home/b/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/frontend/parser.rs:246
  11:     0x7f1016904026 - radeco_lib::frontend::parser::Parser::parse_opinfo::h348d88954b36227e
                        at /home/b/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/frontend/parser.rs:169
  12:     0x7f101689419c - radeco_lib::utils::Runner::parse_esil::hfc6ab52268f60c54
                        at /home/b/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/utils/mod.rs:232
  13:     0x7f10168cf6bd - radeco_lib::utils::Runner::run::hd171b7d46e116dc7
                        at /home/b/.cargo/git/checkouts/radeco-lib-99c1e75dd493d005/master/src/utils/mod.rs:335
  14:     0x7f1016880872 - radeco::args::Radeco::run::h8162181c943bbb6f
                        at src/args.rs:218
  15:     0x7f10168315b1 - radeco::main::hef71af336d3ef19f
                        at src/main.rs:39
  16:     0x7f1016b20674 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  17:     0x7f1016b1bdfb - __rust_try
  18:     0x7f1016b200bb - std::rt::lang_start::h5b0863080165c75e
  19:     0x7f101683e8a9 - main
  20:     0x7f1015c0ef44 - __libc_start_main
  21:     0x7f1016831118 - <unknown>
  22:                0x0 - <unknown>
```

Radeco installed using r2pm, reported version is 0.1.0.

**Comment by sushant94** [comment]
This is fixed in the latest version of radeco-lib, but since this won't be in sync with radeco, the changes are currently unmerged in the form of a PR (see #31). Once I make the necessary changes in radeco (to use the latest radeco-lib) this will be fixed.

**Comment by sushant94** [comment]
If you'd like to give radeco a try now, please check [src/minidec](https://github.com/radare/radeco-lib/tree/master/minidec) on information on how to. More bug reports after are welcome :)

**Comment by ZhangZhuoSJTU** [comment]
Closed.
