### ISSUE TITLE
panic on unwrap with minidec

### ISSUE THREAD

**Issue by crowell** [radare/radeco-lib#32]
```
[0x00400526]> #!pipe RUST_BACKTRACE=1 ./minidec
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[0x0040053e esil_mem_addeq_n: invalid parameterse)
[x] Emulate code to find computed references (aae)
[x] Analyze consecutive function (aat)
[aav: using from to 0x400000 0x402198
Using vmin 0x400000 and vmax 0x601040
aav: using from to 0x400000 0x402198
Using vmin 0x400000 and vmax 0x601040
[x] Analyze value pointers (aav)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[*] Constructing ...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x555f02d872ef - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x555f02d8c0db - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x555f02d8bd63 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x555f02d7dccd - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x555f02d8c321 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x555f02d7ec8a - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x555f02d8c2be - rust_begin_unwind
   8:     0x555f02dc1b6f - core::panicking::panic_fmt::h93df64e7370b5253
   9:     0x555f02dc1e48 - core::panicking::panic::h9d5bd65bbb401959
  10:     0x555f02cd3584 - _<std..option..Option<T>>::unwrap::h6aef091f4b6ff42e
                        at ../src/libcore/macros.rs:21
  11:     0x555f02cd3357 - _<middle..phiplacement..PhiPlacer<'a, T>>::read_register::h4ead5c0b182be7fe
                        at src/middle/phiplacement.rs:447
  12:     0x555f02ce2339 - _<frontend..ssaconstructor..SSAConstruct<'a, T>>::process_in::hd7618884e7f30e12
                        at src/frontend/ssaconstructor.rs:127
  13:     0x555f02ce0dd1 - _<frontend..ssaconstructor..SSAConstruct<'a, T>>::process_op::h4d0dd0078e677458
                        at src/frontend/ssaconstructor.rs:180
  14:     0x555f02cb3b4e - _<frontend..ssaconstructor..SSAConstruct<'a, T>>::run::h1b082c3ed2f8d414
                        at src/frontend/ssaconstructor.rs:482
  15:     0x555f02ca0ae3 - radeco_lib::frontend::containers::RadecoFunction::construct::h5d9b65935b8ad2d2
                        at src/frontend/containers.rs:100
  16:     0x555f02ce94ac - radeco_lib::frontend::containers::ssa_single_fn::he5096a7f47bddb01
                        at src/frontend/containers.rs:123
  17:     0x555f02bf5c4a - _<radeco_lib..frontend..containers..RadecoModule<'a> as std..convert..From<&'a mut T>>::from::_$u7b$$u7b$closure$u7d$$u7d$::hb44788f1fdd653c6
  18:     0x555f02bf5b37 - _<std..panic..AssertUnwindSafe<F> as std..ops..FnOnce<()>>::call_once::h527d3b6640403128
                        at ../src/libstd/panic.rs:284
  19:     0x555f02bf5a8e - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h3f5128ea6bbad281
  20:     0x555f02bf63d4 - std::panicking::try::call::h7da9b03a87cc71a2
                        at ../src/libstd/panicking.rs:272
  21:     0x555f02d95d2b - __rust_try
  22:     0x555f02d95cce - __rust_maybe_catch_panic
  23:     0x555f02bf571d - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::hf4d7c48fcd75690f
  24:     0x555f02bf55ef - _<std..thread..LocalKey<T>>::with::hfba6cb75f1a19d58
                        at ../src/libstd/thread/local.rs:211
  25:     0x555f02bf542f - std::panicking::try::h8b85037222c3ea8b
                        at ../src/libstd/panicking.rs:235
  26:     0x555f02bf530e - std::panic::catch_unwind::h6af3f394e3201ad9
                        at ../src/libstd/panic.rs:387
  27:     0x555f02bf5181 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::he15378db27dde864
  28:     0x555f02bf6757 - _<F as std..boxed..FnBox<A>>::call_box::h765aff2a4682d6c1
                        at ../src/liballoc/boxed.rs:543
  29:     0x555f02d8a914 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  30:     0x7fd32f6c66f9 - start_thread
  31:     0x7fd32f1e6b5c - clone
  32:                0x0 - <unknown>
[+] Analyzing: sub.__gmon_start___248_420 @ 0x400420
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.frame_dummy @ 0x400500
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.__libc_csu_init @ 0x400570
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.__do_global_dtors_aux @ 0x4004e0
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.register_tm_clones @ 0x4004a0
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: entry0 @ 0x400430
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym._init @ 0x4003c8
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.deregister_tm_clones @ 0x400460
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym.__libc_csu_fini @ 0x4005e0
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
[+] Analyzing: sym._fini @ 0x4005e4
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
  [*] Eliminating Common SubExpressions
  [*] Writing out IR
```

binary (base64'd) https://gist.github.com/a44b88d77df07c1b6486204eaee34f44

**Comment by sushant94** [comment]
This may be because the function uses xmm registers. Currently, radeco does not support these.

**Comment by radare** [comment]
Will be nice to make radeco show more meaningful errors with context

**Comment by ZhangZhuoSJTU** [comment]
This is because float is not supported in Radeco, thus missing the xmm0..4 registers.
