### ISSUE TITLE
minidec: thread main panicked at called Option::unwrap() on a None value

### ISSUE THREAD

**Issue by resetnow** [radare/radeco-lib#41]
I have seen similar "unwrap on none" issues, but this one seems to happen in a different source location.

```
[+] Analyzing: fcn.402119dc @ 0x402119dc
  [*] Eliminating Dead Code
  [*] Propagating Constants
  [*] Eliminating More DeadCode
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:325
stack backtrace:
   1:     0x55a94460f641 - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55a944614c41 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55a94461487c - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55a9446057c4 - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55a944614ece - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55a94460636f - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55a944614e77 - rust_begin_unwind
   8:     0x55a94461eb5d - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x55a94461ee03 - core::panicking::panic::heeca72c448510af4
  10:     0x55a9444ddad2 - _<core..option..Option<T>>::unwrap::hf974143bfcbe386e
                        at /builddir/build/BUILD/rustc-1.11.0/src/libcore/macros.rs:21
  11:     0x55a9444dd618 - radeco_lib::middle::ssa::ssastorage::SSAStorage::external::h1f5b13fa02c4fa7d
                        at /opt/radeco-lib/src/middle/ssa/ssastorage.rs:233
  12:     0x55a9444e47c3 - _<radeco_lib..middle..ssa..ssastorage..SSAStorage as radeco_lib..middle..ssa..cfg_traits..CFG>::exit_node::h63e586e9c197f278
                        at /opt/radeco-lib/src/middle/ssa/ssastorage.rs:337
  13:     0x55a94447c708 - radeco_lib::middle::dce::sweep::h725eb14d32f93186
                        at /opt/radeco-lib/src/middle/dce.rs:64
  14:     0x55a94447a32d - radeco_lib::middle::dce::collect::h52dafd5a519e870c
                        at /opt/radeco-lib/src/middle/dce.rs:20
  15:     0x55a944436ef7 - minidec::main::he08289d7edeea7b6
                        at /opt/radeco-lib/minidec/main.rs:46
  16:     0x55a94461445d - std::panicking::try::call::hca715a47aa047c49
  17:     0x55a94461c36b - __rust_try
  18:     0x55a94461c315 - __rust_maybe_catch_panic
  19:     0x55a944613ec9 - std::rt::lang_start::h162055cb2e4b9fe7
  20:     0x55a9444ad6c9 - main
  21:     0x7fac33c60730 - __libc_start_main
  22:     0x55a944436398 - _start
  23:                0x0 - <unknown>
```

I can share the binary if necessary.

**Comment by sushant94** [comment]
Ok, this seems like a different issue and has something to do with accessing a node that does not exist. Could you please generate a log and attach it to the issue? That would help me a ton. If the binary is redistributable, please add a copy of that too.

**Comment by sushant94** [comment]
Ok, seems like I don't have instructions on how to generate logs anywhere. I'll add that to minidec soon. But in the meanwhile if you can, please point me to the binary that causes this.

**Comment by resetnow** [comment]
Binary: https://resetnow.ru/temp/r2-xtensa-crash

**Comment by uxmal** [comment]
When I try to open that binary with `objdump` I get the error `File truncated`. Is it just me?

**Comment by resetnow** [comment]
It appears it's broken, sorry! I will reupload it in about 6 hours.

**Comment by resetnow** [comment]
Just remembered I shared it on Telegram earlier 

[esp8266-display.zip](https://github.com/radare/radeco-lib/files/495131/esp8266-display.zip)
